### ISSUE TITLE
After I setup .env, I am getting error from client.ts

### ISSUE THREAD

**Issue by madanbazgai** [upstash/jstack#9]
![image](https://github.com/user-attachments/assets/7d6e8d35-4490-4957-b18b-2017de84ca45)

**Comment by saeidex** [comment]
create migration after env setup

```shell
bun x prisma migrate dev --name init
```

ref: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/using-prisma-migrate-typescript-postgresql

**Comment by madanbazgai** [comment]
Solved, thanks mate,
I missed this one, i was just running "postinstall": "prisma generate"
